### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by LeabaeL** [yuezhengfu/CNPS.cycle#1]
Hi yuezhengfu!

Thank you for developing this R package for conveniently obtaining CNPS elemental cyclograms and corresponding analytical results. However, I am now unable to install it correctly by following the steps in the tutorial.

My R version is 4.3.2.

Looking forward to your reply.

Best Regards!
LeabaeL

**Comment by yuezhengfu** [comment]
> Hi yuezhengfu!
> 
> Thank you for developing this R package for conveniently obtaining CNPS elemental cyclograms and corresponding analytical results. However, I am now unable to install it correctly by following the steps in the tutorial.
> 
> My R version is 4.3.2.
> 
> Looking forward to your reply.
> 
> Best Regards! LeabaeL

Hello,
Can you provide specific error details? If convenient, please provide a screenshot

**Comment by LeabaeL** [comment]
![image](https://github.com/yuezhengfu/CNPS.cycle/assets/68262614/234a8b40-8e6e-4ce4-88c3-b077ffd03335)

**Comment by yuezhengfu** [comment]
please download zip, and attempt an offline installation.


此致
         敬礼！


岳政府
=============================
Dr. Yue zhengfu
Environmental and Plant Protection Institute
Chinese Academy of Tropical Agricultural Sciences
4 Xueyuan Rd, Haikou 571101, China
=============================
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/8/2024 15:36 |
| To | ***@***.***> |
| Cc | Zhengfu ***@***.***> ,
***@***.***> |
| Subject | Re: [yuezhengfu/CNPS.cycle] Can't install (Issue #1) |

image.png (view on web)

**Comment by LeabaeL** [comment]
我尝试了离线安装，也尝试了直接将下载的压缩包解压复制到安装目录中，但仍然无法使用。
![image](https://github.com/yuezhengfu/CNPS.cycle/assets/68262614/5d87d77e-eb10-4849-b42a-d6544c366ac2)

**Comment by yuezhengfu** [comment]
根据提示来看，请确保您从github上下载的压缩包中包含DESCRIPTION文件。另外，请不要直接将压缩包解压至安装目录中，该包需要好多个依赖包，直接解压是无法正常使用的。我为您提供了我这边测试后的本地安装压缩包，这个我刚测试过没有问题。


此致
         敬礼！


岳政府
=============================
Dr. Yue zhengfu
Environmental and Plant Protection Institute
Chinese Academy of Tropical Agricultural Sciences
4 Xueyuan Rd, Haikou 571101, China
=============================
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/8/2024 15:53 |
| To | ***@***.***> |
| Cc | Zhengfu ***@***.***> ,
***@***.***> |
| Subject | Re: [yuezhengfu/CNPS.cycle] Can't install (Issue #1) |

我尝试了离线安装，也尝试了直接将下载的压缩包解压复制到安装目录中，但仍然无法使用。
image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| CNPS.cycle_1.0.0.tar.gz |
| |
| (50.7MB,2024年1月23日 16:4 到期) |
| |
| 下载 |
| |
| |

**Comment by LeabaeL** [comment]
似乎您提供的安装包无法打开
![image](https://github.com/yuezhengfu/CNPS.cycle/assets/68262614/1ac221da-5a8a-450a-8c67-0904ef656b79)

**Comment by yuezhengfu** [comment]
附件大于25M了，请提供您的邮箱


此致
         敬礼！


岳政府
=============================
Dr. Yue zhengfu
Environmental and Plant Protection Institute
Chinese Academy of Tropical Agricultural Sciences
4 Xueyuan Rd, Haikou 571101, China
=============================
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/8/2024 16:16 |
| To | ***@***.***> |
| Cc | Zhengfu ***@***.***> ,
***@***.***> |
| Subject | Re: [yuezhengfu/CNPS.cycle] Can't install (Issue #1) |

似乎您提供的安装包无法打开
image.png (view on web)

**Comment by LeabaeL** [comment]
It seems that the tar.gz-compressed installer sent by the author can be installed properly locally and requires "ggimage" to be installed in advance, thanks again for the prompt reply and help!
